### ISSUE TITLE
Error: Not the latest build

### ISSUE THREAD

**Issue by morph027** [YuMS/gitlab-ce-pages#11]
This is what i get with latest Gitlab 8.12.4 and GCP 1.2.1 (replaced url and token)

```
Only care about succeed builds
Only care about succeed builds
check_latest options { url: 'http://my-gitlab.example.com/api/v3/projects/9/builds?scope=success',
  headers: { 'PRIVATE-TOKEN': 'XXX' } }
Error: Not the latest build
    at Request.request.get.e [as _callback] (/home/pages/webhook/deployer.js:99:25)
    at Request.self.callback (/home/pages/webhook/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pages/webhook/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pages/webhook/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

**Comment by morph027** [comment]
Ah, ok, my fault, while replacing the url, i've noticed that i was not using https ;)
